In [1]:
import pymoldis

df=pymoldis.get_data('bigqm7w_S1T1')
df.describe()

,Natoms,S1_SCSPBEQIDH(eV),T1_SCSPBEQIDH(eV),f01_SCSPBEQIDH(au),S1_ADC2(eV),T1_ADC2(eV),f01_ADC2(au)
count,12879.000000,12879.000000,12879.000000,12879.000000,12879.000000,12879.000000,12879.000000
mean,14.412144,6.287543,4.989370,0.099150,6.080681,5.009070,0.085172
std,2.907145,1.220643,1.372904,0.218265,1.196321,1.277183,0.169825
min,2.000000,1.809000,0.957000,0.000000,1.708240,0.945684,0.000000
25%,12.000000,5.657500,4.038000,0.001136,5.465241,4.093702,0.001144
50%,14.000000,6.393000,4.568000,0.007151,6.189377,4.732365,0.010504
75%,16.000000,7.011000,5.616000,0.050613,6.818060,5.924219,0.073313
max,23.000000,14.339000,13.844000,1.785412,14.010585,13.599737,1.362576

In [2]:
df.columns

Index(['SMI', 'Natoms', 'atoms', 'coords(Ang)', 'S1_SCSPBEQIDH(eV)',
       'T1_SCSPBEQIDH(eV)', 'f01_SCSPBEQIDH(au)', 'S1_ADC2(eV)', 'T1_ADC2(eV)',
       'f01_ADC2(au)'],
      dtype='object')